[package]
name = "write-polkadot"
version = "0.1.0"
authors = ["Shubham Arora <aroras@bu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
